# -*- coding: utf-8 -*-
"""Olá, este é o Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd

df = pd.read_csv('/content/sample_data/Teste - Clima x Tempo Util x Processamento.csv', sep=';')

df1 = []
with open('/content/sample_data/Teste - Clima x Tempo Util x Processamento.csv','r') as arq:
  for i in arq:
    aux = i.split('\n')
    for y in aux:
      aux1 = y.split(';')
      if y != aux[0]:
        aux1[1:] = map(lambda x: float(x),aux1[1:])
      df1.append(aux1) if aux1 != [''] else None

def converte_virg(lista, i):
  lista[i] = lista[i].replace(',','.')
  return

for aux2 in df1:
  for i in [1,2,3]:
    converte_virg(aux2,i)

df = pd.DataFrame(df1)
df.columns = df.iloc[0,:]
df = df.iloc[1:,:]
df.Data = pd.to_datetime(df.Data)
df.Entrada,df.Chuva,df.Parada = map(lambda x: pd.to_numeric(x),[df.Entrada,df.Chuva,df.Parada])